title: Smitha Lingadahalli Ravi
logo: /assets/Photo1.jpg
description: PhD @ Orange Labs & University of Rennes 1, France
linkedin: https://www.linkedin.com/in/smitha-lingadahalli-ravi-03760b20a/
show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
